fix(rlp): revert change due to error
file:///Users/msfew/github/zkgraph-api/dist/index.mjs:278
    for (let i = 0; i < rlpevents.length; i++) {
                                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Function.fromRawBin (file:///Users/msfew/github/zkgraph-api/dist/index.mjs:278:35)
    at Function.fromRawStr (file:///Users/msfew/github/zkgraph-api/dist/index.mjs:284:22)
    at rlpDecodeAndEventFilter (file:///Users/msfew/github/zkgraph-api/dist/index.mjs:374:26)
    at filterEvents (file:///Users/msfew/github/zkgraph-api/dist/index.mjs:421:55)
    at Module.executeOnRawReceipts (file:///Users/msfew/github/zkgraph-api/dist/index.mjs:941:52)
    at file:///Users/msfew/github/zkgraph/api/exec.js:55:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)